### ISSUE TITLE
Find method is incomplete

### ISSUE THREAD

**Issue by ramesshh** [marklap/jsonpath-lua#1]
**This is not an issue, a request only.**

` find` method from `jsonpath.lua` file is incomplete. Could you please update the completed code.
I would highly appreciate your help.
Thanks

**Comment by marklap** [comment]
This was just an experiment I did years ago. I wanted to see if I could write a parser and lexer and it seemed like a simple project to tackle. Almost as soon as I get something barely working, I found JMESPath. They have a lua library. It's almost exactly the same as jsonpath.

http://jmespath.org/
http://jmespath.org/libraries.html
https://github.com/jmespath/jmespath.lua

I won't be making any updates to this project so I suggest forking and changing to suit your needs or using JMESPath.
